/* eslint-disable @typescript-eslint/no-explicit-any */
import { PrismaClient, Prisma, TransferStatus } from "@prisma/client";
import bcrypt from "bcryptjs";
import { promises as fs } from "fs";
import path from "path";
import { generateTransferReference } from "../src/lib/reference";
import { buildQuote } from "../src/lib/quote";

const prisma = new PrismaClient();

function placeholderSvg(label: string, name: string, accent = "#FFB400"): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="480" height="300" viewBox="0 0 480 300">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#0B2545"/>
      <stop offset="1" stop-color="#13315C"/>
    </linearGradient>
  </defs>
  <rect width="480" height="300" fill="url(#bg)"/>
  <rect x="16" y="16" width="448" height="268" fill="none" stroke="${accent}" stroke-width="2" stroke-dasharray="6 4"/>
  <text x="32" y="56" font-family="Inter, sans-serif" font-size="14" fill="${accent}" font-weight="700" letter-spacing="2">DEMO PLACEHOLDER</text>
  <text x="32" y="118" font-family="Inter, sans-serif" font-size="34" fill="white" font-weight="700">${label}</text>
  <text x="32" y="160" font-family="Inter, sans-serif" font-size="20" fill="#E8EEF7">${name}</text>
  <text x="32" y="200" font-family="ui-monospace, monospace" font-size="12" fill="#9BA8B8">Document #ZP-${Math.floor(Math.random() * 900000 + 100000)}</text>
  <text x="32" y="222" font-family="ui-monospace, monospace" font-size="12" fill="#9BA8B8">Issued: 2024-08-12 · Expires: 2034-08-12</text>
  <text x="32" y="270" font-family="Inter, sans-serif" font-size="11" fill="#9BA8B8">Generated by seed.ts (not a real document)</text>
  <circle cx="420" cy="60" r="20" fill="${accent}" opacity="0.85"/>
  <text x="420" y="66" font-family="Inter, sans-serif" font-size="14" fill="#0B1A2C" font-weight="700" text-anchor="middle">Z</text>
</svg>`;
}

async function writeKycSvg(userId: string, docType: string, fullName: string): Promise<{ filePath: string; sizeBytes: number }> {
  const dir = path.join(process.cwd(), "kyc-uploads", userId);
  await fs.mkdir(dir, { recursive: true });
  const labels: Record<string, string> = {
    id_front: "ID FRONT",
    id_back: "ID BACK",
    selfie: "SELFIE",
  };
  const svg = placeholderSvg(labels[docType] ?? docType.toUpperCase(), fullName);
  const filename = `${docType}-seed.svg`;
  const fullPath = path.join(dir, filename);
  await fs.writeFile(fullPath, svg, "utf-8");
  return {
    filePath: path.relative(process.cwd(), fullPath),
    sizeBytes: Buffer.byteLength(svg, "utf-8"),
  };
}

const PASSWORD_HASH = bcrypt.hashSync("password123", 10);

async function main() {
  console.log("Seeding Zarpay…");

  // Wipe
  await prisma.auditLog.deleteMany();
  await prisma.complianceFlag.deleteMany();
  await prisma.transferEvent.deleteMany();
  await prisma.supportMessage.deleteMany();
  await prisma.supportTicket.deleteMany();
  await prisma.transfer.deleteMany();
  await prisma.recipient.deleteMany();
  await prisma.kycDocument.deleteMany();
  await prisma.exchangeRate.deleteMany();
  await prisma.user.deleteMany();

  // ---- Users ----
  const admin = await prisma.user.create({
    data: {
      email: "admin@zarpay.dev",
      fullName: "Atif Admin",
      phone: "+447000000001",
      passwordHash: PASSWORD_HASH,
      role: "admin",
      kycStatus: "approved",
      kycTier: 2,
      country: "GB",
    },
  });
  const reviewer = await prisma.user.create({
    data: {
      email: "reviewer@zarpay.dev",
      fullName: "Rana Reviewer",
      phone: "+447000000002",
      passwordHash: PASSWORD_HASH,
      role: "reviewer",
      kycStatus: "approved",
      kycTier: 2,
      country: "GB",
    },
  });
  const compliance = await prisma.user.create({
    data: {
      email: "compliance@zarpay.dev",
      fullName: "Cara Compliance",
      phone: "+447000000003",
      passwordHash: PASSWORD_HASH,
      role: "compliance",
      kycStatus: "approved",
      kycTier: 2,
      country: "GB",
    },
  });

  const senderSpecs = [
    {
      email: "sender@zarpay.dev",
      fullName: "Sara Khan",
      phone: "+447701234567",
      city: "Birmingham",
      postcode: "B1 1AA",
      kycStatus: "approved" as const,
    },
    {
      email: "imran@example.com",
      fullName: "Imran Rashid",
      phone: "+447702345678",
      city: "London",
      postcode: "E1 6AN",
      kycStatus: "approved" as const,
    },
    {
      email: "fatima@example.com",
      fullName: "Fatima Begum",
      phone: "+447703456789",
      city: "Manchester",
      postcode: "M1 1AE",
      kycStatus: "approved" as const,
    },
    {
      email: "yusuf@example.com",
      fullName: "Yusuf Ali",
      phone: "+447704567890",
      city: "Bradford",
      postcode: "BD1 1JP",
      kycStatus: "pending" as const,
    },
    {
      email: "newbie@example.com",
      fullName: "Aisha Mahmood",
      phone: "+447705678901",
      city: "Luton",
      postcode: "LU1 2NQ",
      kycStatus: "unverified" as const,
    },
  ];

  const senders = await Promise.all(
    senderSpecs.map((s) =>
      prisma.user.create({
        data: {
          email: s.email,
          fullName: s.fullName,
          phone: s.phone,
          passwordHash: PASSWORD_HASH,
          role: "sender",
          kycStatus: s.kycStatus,
          kycTier: s.kycStatus === "approved" ? 1 : 0,
          country: "GB",
          city: s.city,
          postcode: s.postcode,
          addressLine1: `${Math.floor(Math.random() * 200) + 1} High Street`,
          dateOfBirth: new Date(1990, 0, 1),
        },
      }),
    ),
  );

  // KYC documents for the pending sender. Write real SVG placeholders so the
  // reviewer's side-by-side viewer has something to display in the demo.
  const yusuf = senders.find((s) => s.email === "yusuf@example.com");
  if (yusuf) {
    for (const docType of ["id_front", "id_back", "selfie"] as const) {
      const stored = await writeKycSvg(yusuf.id, docType, yusuf.fullName);
      await prisma.kycDocument.create({
        data: {
          userId: yusuf.id,
          docType,
          filePath: stored.filePath,
          mimeType: "image/svg+xml",
          sizeBytes: stored.sizeBytes,
          status: "pending",
        },
      });
    }
  }

  // Approved sender Sara Khan also has KYC docs on file (already approved) so
  // an admin viewing her profile can still see her documents.
  const sara = senders.find((s) => s.email === "sender@zarpay.dev");
  if (sara) {
    for (const docType of ["id_front", "id_back", "selfie"] as const) {
      const stored = await writeKycSvg(sara.id, docType, sara.fullName);
      await prisma.kycDocument.create({
        data: {
          userId: sara.id,
          docType,
          filePath: stored.filePath,
          mimeType: "image/svg+xml",
          sizeBytes: stored.sizeBytes,
          status: "approved",
          reviewedById: reviewer.id,
          reviewedAt: new Date(),
        },
      });
    }
  }

  // ---- Recipients (4 per approved sender) ----
  const PK_NAMES = [
    "Bilal Hussain",
    "Hina Iqbal",
    "Asad Mehmood",
    "Sana Tariq",
    "Kamran Sheikh",
    "Mehwish Akhtar",
    "Tariq Aziz",
    "Nida Farooq",
    "Owais Anwar",
    "Saima Saleem",
    "Junaid Bashir",
    "Rabia Naseer",
    "Faisal Mahmud",
    "Zara Riaz",
    "Adnan Pervez",
    "Anum Shahid",
    "Hamza Qureshi",
    "Ayesha Malik",
    "Salman Yousaf",
    "Maryam Javed",
  ];
  let nameIdx = 0;
  const approvedSenders = senders.filter((s) => s.kycStatus === "approved");
  const allRecipients: Array<{ id: string; senderId: string }> = [];

  for (const sender of approvedSenders) {
    for (let i = 0; i < 4; i++) {
      const name = PK_NAMES[nameIdx++ % PK_NAMES.length];
      const method = i === 0 ? "bank" : i === 1 ? "mobile_wallet" : i === 2 ? "cash_pickup" : "bank";
      let accountDetails: Record<string, unknown> = {};
      if (method === "bank") {
        const banks = ["HBL", "MCB", "UBL", "MEEZAN", "BAFL"];
        accountDetails = {
          bank_code: banks[Math.floor(Math.random() * banks.length)],
          account_number: String(Math.floor(Math.random() * 9_000_000_000) + 1_000_000_000),
          account_title: name,
        };
      } else if (method === "mobile_wallet") {
        accountDetails = {
          provider: ["easypaisa", "jazzcash", "nayapay"][i % 3],
          account_number: `030${Math.floor(Math.random() * 90_000_000 + 10_000_000)}`,
        };
      } else {
        accountDetails = {
          network: i % 2 === 0 ? "western_union" : "moneygram",
          full_name: name,
        };
      }
      const r = await prisma.recipient.create({
        data: {
          userId: sender.id,
          fullName: name,
          nickname: i === 0 ? "Family" : null,
          relationship: i === 0 ? "Family" : i === 1 ? "Friend" : null,
          payoutMethod: method as any,
          accountDetails: accountDetails as any,
          phone: `+9230${Math.floor(Math.random() * 90_000_000 + 10_000_000)}`,
          isVerified: true,
        },
      });
      allRecipients.push({ id: r.id, senderId: sender.id });
    }
  }

  // ---- Exchange rate snapshot ----
  await prisma.exchangeRate.create({
    data: {
      base: "GBP",
      quote: "PKR",
      midRate: new Prisma.Decimal("365.42"),
      spreadBps: 120,
      effectiveAt: new Date(),
      source: "frankfurter",
    },
  });

  // ---- Transfers (30 across all states) ----
  const STATES: TransferStatus[] = [
    "delivered",
    "delivered",
    "delivered",
    "delivered",
    "delivered",
    "delivered",
    "delivered",
    "delivered",
    "delivered",
    "delivered",
    "delivered",
    "delivered",
    "in_transit",
    "in_transit",
    "in_transit",
    "funded",
    "funded",
    "compliance_hold",
    "compliance_hold",
    "pending_payment",
    "pending_payment",
    "quote_locked",
    "cancelled",
    "cancelled",
    "rejected",
    "delivered",
    "delivered",
    "delivered",
    "in_transit",
    "delivered",
  ];

  const AMOUNTS = [
    50, 100, 150, 200, 250, 300, 400, 500, 600, 750, 800, 1000, 1200, 1500, 200,
    350, 80, 1500, 2500, 60, 90, 250, 100, 200, 1800, 75, 120, 180, 220, 95,
  ];

  let now = Date.now();
  for (let i = 0; i < STATES.length; i++) {
    const state = STATES[i];
    const recipient = allRecipients[i % allRecipients.length];
    const amount = AMOUNTS[i % AMOUNTS.length];

    const quote = buildQuote({
      sendAmountGbp: amount,
      midRate: "365.42",
      spreadBps: 120,
      feeGbp: "1.99",
    });

    const createdAt = new Date(now - i * 6 * 60 * 60 * 1000); // every 6h back
    const reference = generateTransferReference();

    const initiatedAt = createdAt;
    const fundedAt =
      state === "funded" ||
      state === "compliance_hold" ||
      state === "in_transit" ||
      state === "delivered" ||
      state === "rejected"
        ? new Date(initiatedAt.getTime() + 90_000)
        : null;
    const inTransitAt =
      state === "in_transit" || state === "delivered"
        ? new Date(initiatedAt.getTime() + 200_000)
        : null;
    const deliveredAt = state === "delivered" ? new Date(initiatedAt.getTime() + 600_000) : null;

    const t = await prisma.transfer.create({
      data: {
        reference,
        senderId: recipient.senderId,
        recipientId: recipient.id,
        sendAmountGbp: new Prisma.Decimal(quote.sendAmountGbp.toString()),
        receiveAmountPkr: new Prisma.Decimal(quote.receiveAmountPkr.toString()),
        exchangeRate: new Prisma.Decimal(quote.effectiveRate.toString()),
        spreadBps: 120,
        feeGbp: new Prisma.Decimal(quote.feeGbp.toString()),
        totalChargedGbp: new Prisma.Decimal(quote.totalChargedGbp.toString()),
        status: state,
        paymentIntentId: state !== "quote_locked" ? `pi_seed_${i}` : null,
        payoutReference: inTransitAt ? `po_seed_${i}` : null,
        quoteLockedUntil: new Date(initiatedAt.getTime() + 60 * 60 * 1000),
        initiatedAt,
        fundedAt,
        inTransitAt,
        deliveredAt,
        createdAt,
      },
    });

    // Add events for the realistic transitions
    const events: Array<{ event: string; toStatus: string; at: Date; fromStatus?: string }> = [
      { event: "quote_created", toStatus: "quote_locked", at: createdAt },
    ];
    if (state !== "quote_locked") {
      events.push({
        event: "payment_initiated",
        toStatus: "pending_payment",
        fromStatus: "quote_locked",
        at: new Date(createdAt.getTime() + 5_000),
      });
    }
    if (fundedAt) {
      events.push({
        event: "payment_funded",
        toStatus: "funded",
        fromStatus: "pending_payment",
        at: fundedAt,
      });
    }
    if (state === "compliance_hold") {
      events.push({
        event: "compliance_flagged",
        toStatus: "compliance_hold",
        fromStatus: "funded",
        at: new Date(fundedAt!.getTime() + 1_000),
      });
    }
    if (inTransitAt) {
      events.push({
        event: "released_to_payout",
        toStatus: "in_transit",
        fromStatus: state === "compliance_hold" ? "compliance_hold" : "funded",
        at: inTransitAt,
      });
    }
    if (deliveredAt) {
      events.push({
        event: "payout_delivered",
        toStatus: "delivered",
        fromStatus: "in_transit",
        at: deliveredAt,
      });
    }
    if (state === "cancelled") {
      events.push({
        event: "payment_cancelled",
        toStatus: "cancelled",
        fromStatus: "pending_payment",
        at: new Date(createdAt.getTime() + 60_000),
      });
    }
    if (state === "rejected") {
      events.push({
        event: "manual_state_change",
        toStatus: "rejected",
        fromStatus: "compliance_hold",
        at: new Date(createdAt.getTime() + 1_200_000),
      });
    }

    for (const e of events) {
      await prisma.transferEvent.create({
        data: {
          transferId: t.id,
          eventType: e.event as any,
          fromStatus: e.fromStatus ?? null,
          toStatus: e.toStatus,
          actorType: "system",
          createdAt: e.at,
          payload: {} as any,
        },
      });
    }

    // Add compliance flags for hold/large/rejected states
    if (state === "compliance_hold" || (amount >= 1000 && state !== "quote_locked")) {
      await prisma.complianceFlag.create({
        data: {
          transferId: t.id,
          rule: "amount_threshold",
          severity: amount >= 2000 ? "high" : "medium",
          status: state === "compliance_hold" ? "open" : "cleared",
          notes: `Single transfer of £${amount.toFixed(2)} crosses the £1000 review threshold.`,
          reviewedById: state === "compliance_hold" ? null : compliance.id,
          reviewedAt: state === "compliance_hold" ? null : new Date(),
        },
      });
    }
  }

  // ---- Audit log entries ----
  await prisma.auditLog.createMany({
    data: [
      {
        actorId: reviewer.id,
        action: "kyc.approve",
        targetType: "user",
        targetId: senders[0].id,
        diff: { kycStatus: { from: "pending", to: "approved" } } as any,
      },
      {
        actorId: admin.id,
        action: "rate.refresh",
        targetType: "exchange_rate",
        targetId: "seed",
        diff: { midRate: "365.42", spreadBps: 120 } as any,
      },
      {
        actorId: compliance.id,
        action: "compliance.clear",
        targetType: "compliance_flag",
        targetId: "seed",
        diff: {} as any,
      },
    ],
  });

  console.log("Done.");
  console.log("");
  console.log("Demo accounts (password: password123)");
  console.log("  admin@zarpay.dev      : full admin");
  console.log("  reviewer@zarpay.dev   : KYC reviewer");
  console.log("  compliance@zarpay.dev : compliance officer");
  console.log("  sender@zarpay.dev     : approved sender (Sara Khan)");
  console.log("  imran@example.com     : approved sender");
  console.log("  fatima@example.com    : approved sender");
  console.log("  yusuf@example.com     : pending KYC review");
  console.log("  newbie@example.com    : unverified, no KYC yet");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
